services:

  pgsql:
    image: postgres:16.4
    environment:
      POSTGRES_USER: data-quality
      POSTGRES_PASSWORD: data-quality
      POSTGRES_HOST_AUTH_METHOD: md5
    ports:
      - "5432:5432"
    volumes:
      - db_data_data-quality-filter-service:/var/lib/postgresql/data

  data-quality-filter-service:
    image: sbdi/data-quality-filter-service-dev
    build:
      context: .
    environment:
      - JAVA_OPTS=-Xmx1g -Xms128m -Xss256k -Djava.awt.headless=true
    volumes:
      - ./sbdi/data/config/data-quality-filter-service-config.properties:/data/data-quality-filter-service/config/data-quality-filter-service-config.properties
    ports:
      - "8082:8080"

volumes:
  db_data_data-quality-filter-service:
